Sub1
HARUMI-g/cookpad-app pull request #7
Opened 2019-11-02 00:04 UTC by HARUMI-g

トップページの作成

2019-11-02 00:51 UTC, toyokappa requested changes
レビューしました。また、各ディレクトリ内に`.DS_Store`というファイルがGitの管理下に置かれてしまっています。これは管理不要なファイルとなるので`.gitignore`で管理から外すようにしてください。

2019-11-02 00:51 UTC, toyokappa commented on README.md
> +
READMEを更新するのであれば前半のデフォルトの部分は削除してください。

2019-11-02 00:51 UTC, toyokappa commented on app/assets/stylesheets/top.css
> +
home.scssが自動で作成されていると思うのでそちらに書いたほうが良いです。

2019-11-02 00:51 UTC, toyokappa commented on app/helpers/home_helper.rb
> +module HomeHelper
このファイルは不要なので削除してください。

2019-11-02 00:51 UTC, toyokappa commented on app/views/home/top.html.erb
> +
この５行の改行が意味することは何でしょうか？
開発において改行も意味を持って行う意識が重要で、不要な改行は極力行なわないようにしてください。

2019-11-02 00:51 UTC, toyokappa commented on config/routes.rb
> +  get 'home/top'
rootページとなるかと思うので、`root`で定義するようにしてください。

2019-11-02 00:51 UTC, toyokappa commented on test/controllers/home_controller_test.rb
> +require 'test_helper'
このファイルも使うことがなければ削除してください。

2019-11-05 06:18 UTC, HARUMI-g commented
> レビューしました。また、各ディレクトリ内に`.DS_Store`というファイルがGitの管理下に置かれてしまっています。これは管理不要なファイルとなるので`.gitignore`で管理から外すようにしてください。

＞ご指摘ありがとうございます。
＄git rm --cached .DS_Store で削除し、.gitignoreにも記述しました。

2019-11-05 06:19 UTC, HARUMI-g commented on README.md
> +
はい。削除しました。

2019-11-05 06:20 UTC, HARUMI-g commented on app/assets/stylesheets/top.css
> +
top.cssを削除し、home.scssに移動させました。

2019-11-05 06:20 UTC, HARUMI-g commented on app/helpers/home_helper.rb
> +module HomeHelper
削除しました。

2019-11-05 06:21 UTC, HARUMI-g commented on app/views/home/top.html.erb
> +
かしこまりました。改行には気をつけます。

2019-11-05 06:22 UTC, HARUMI-g commented on config/routes.rb
> +  get 'home/top'
記述しました。

2019-11-05 06:22 UTC, HARUMI-g commented on test/controllers/home_controller_test.rb
> +require 'test_helper'
削除しました。

2019-11-05 09:37 UTC, toyokappa commented on app/assets/stylesheets/top.css
> +
Slackで頂いていたエラーの件ですが、拡張子が`.scss`となっているのが分かる通り、通常のCSSとはちょっと書き方が異なります。（一部省略した書き方ができるのでscssの方が楽）

css -> scssに変換できるサイトなどがあるので、そちらを通して変換したのを貼り付けてみてください。また、以後cssを書く際にはscssで書いてみると良いと思います。（ただし学習に時間がかかるようであれば一旦cssで良いです）

2019-11-05 09:47 UTC, toyokappa requested changes
修正の流れ的にはこれで問題ないです。ただ、基礎部分がだいぶ抜けてそうなので、ドキュメント読みながら直してください。

2019-11-05 09:47 UTC, toyokappa commented on app/views/home/top.html.erb
> +    <link rel="stylesheet" href="stylesheets.home.scss">
Slackでもらっていたエラーの原因はこちらです。Railsでstylesheetを設定する方法を調べて設定してください。

2019-11-05 09:47 UTC, toyokappa commented on config/routes.rb
> +  get 'home/top', to:'home#top'
`root`で定義してくださいと記載したのですが、できてないですね。ルーティングの設定の仕方を学びましょう。
https://railsguides.jp/routing.html

2019-11-05 09:47 UTC, toyokappa commented on app/views/home/top.html.erb
> +<!DOCTYPE html>
[app/view/layouts/application.html.erb](https://github.com/HARUMI-g/cookpad-app/blob/master/app/views/layouts/application.html.erb)を無視してベタ書きしているのを見ると、Railsでのレンダリングに関する基礎中の基礎が身についてないです。手漉きに下記を確認してください。
https://railsguides.jp/layouts_and_rendering.html

2019-11-09 03:35 UTC, HARUMI-g commented on config/routes.rb
> +  get 'home/top', to:'home#top'
root 'home#top' で設定しました。

2019-11-09 03:36 UTC, HARUMI-g commented on app/views/home/top.html.erb
> +<!DOCTYPE html>
共通となるCSSをapp/view/layouts/application.html.erbに仕分けして
修正します。

2019-11-10 02:05 UTC, toyokappa requested changes
＞ほとんど修正があたっていませんでした。レビューを依頼する前に、自身で正しく修正が反映されているのかをGitHub上でセルフレビューしてからレビュー依頼を行うように心がけてください。


確認不足で申し訳ありませんでした。
今後気をつけます。

2019-11-10 02:05 UTC, toyokappa commented on .gitignore
> +.DS_Store
:+1:

2019-11-10 02:05 UTC, toyokappa commented on app/views/home/top.html.erb
> +<!DOCTYPE html>
ここ修正されてないです。

2019-11-10 02:05 UTC, toyokappa commented on config/routes.rb
> +  get 'home/top', to:'home#top'
ここも修正されてないです。

2019-11-19 01:49 UTC, HARUMI-g commented on config/routes.rb
> +  get 'home/top', to:'home#top'
ありがとうございます。
Rails.application.routes.draw do
  resource :home
  root 'home#top'
end

こちらは、上記のように設定しました.

2019-11-19 01:50 UTC, HARUMI-g commented on app/views/home/top.html.erb
> +<!DOCTYPE html>
共通のレイアウトをapp/view/layouts/application.html.erbに移動しました。

2019-11-19 01:56 UTC, HARUMI-g commented on config/routes.rb
> +  get 'home/top'
訂正しましたが、大丈夫かしら。

2019-11-19 01:59 UTC, HARUMI-g commented on app/views/home/top.html.erb
> +    <link rel="stylesheet" href="stylesheets.home.scss">
こちらのエラーは解消できました、ありがとうございました。

2019-11-19 02:51 UTC, toyokappa requested changes
直ってないところがまだありました。これは純粋にチェック漏れでしょうか？それとも何を直したら良いのかが理解できていないのでしょうか？

2019-11-19 02:51 UTC, toyokappa commented on config/routes.rb
> +  resource :home
この定義をしている理由を教えて頂けますか？

2019-11-19 02:51 UTC, toyokappa commented on app/views/home/top.html.erb
> +<!DOCTYPE html>
うーん、まだ直ってないですね。何を直すべきかを理解できていますか？

2019-11-19 04:08 UTC, HARUMI-g commented on config/routes.rb
> +  resource :home
こちらにresource :home 書くのは不適切でした。
resourcesメゾットを使うことによって、URLとアクションを自動で紐付けることができる。
リソース名には、モデルのテーブル名など一覧取得や編集などを行う対象となるものを設定するものでした。
そのため、この行は削除いたします。

2019-11-19 05:57 UTC, HARUMI-g commented on config/routes.rb
> +  resource :home
app/views/home/top.html.erb
１
２<!DOCTYPE html>


ごめんなさい、こちらは直すところよく分かっていないです。
空白のスペースがあることが問題かと単純に思いましたが。

2019-11-23 05:47 UTC, HARUMI-g commented on app/views/home/top.html.erb
> +<!DOCTYPE html>
申し訳ありません。
レイアウトの共通部分を削除してなかったという点だったでしょうか。
気づきが遅くて申し訳ありません。

2019-11-24 14:32 UTC, toyokappa commented on app/views/home/top.html.erb
> +<!DOCTYPE html>
はい、そうです。ただ、何故削除でなくコメントアウトでの対応をされているのでしょうか？

2019-11-24 14:33 UTC, toyokappa commented on config/routes.rb
> +  #resource :home
こちらも同じく何故コメントアウトなのでしょう？

2019-11-25 00:49 UTC, HARUMI-g commented on config/routes.rb
> +  #resource :home
すみません、削除すべきでした。
意味のないコメントアウトするのを今後気をつけます。

2019-11-25 00:51 UTC, HARUMI-g commented on app/views/home/top.html.erb
> +<!DOCTYPE html>
特に考えてないで、コメントアウトしていました。
削除いたしました。
今後気をつけます。

2019-11-25 02:38 UTC, toyokappa approved these changes
LGTMです。マージして次進めましょう。

2019-11-25 05:05 UTC, merged